apiVersion: v1
kind: Namespace
metadata:
  name: llm-model
---
apiVersion: v1
kind: Secret
metadata:
  name: oss-secret
  namespace: default
stringData:
  akId: ${AccessKeyId}
  akSecret: ${AccessKeySecret}