AdvancedOptions: false
RuntimeType: Container
DockerFilePath: comfyui-docker/Dockerfile
ServiceType: private
ArtifactSourceType: Dockerfile
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/comfyui-acs
RegionId: ap-southeast-1
CustomParameters: ''
Owner: LYH-RAIN
Branch: main
Platform: github
